wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # fourteen columns
    columns: [21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text with 10 charachters each
    rows: [7, 7, 7, 7, 7, 7, 7, 7]
  refreshInterval: 1
  mods:
    americas_time:
      title: "Time"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        UTC: "Etc/UTC"
        New_York: "America/New_York"
      position:
        top: 0
        left: 0
        height: 1
        width: 2
    weather:
      args: ["0"]
      cmd: "wego"
      enabled: true
      type: "cmdrunner"
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 100   
    ip:
      type: ipinfo
      title: "IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 9
        height: 1
        width: 2
      refreshInterval: 150
    security_info:
      type: security
      title: "Network"
      enabled: true
      position:
        top: 0
        left: 8
        height: 1
        width: 1
      refreshInterval: 3600
    feedreader:
      enabled: true
      feeds:
      - http://wtfutil.com/blog/index.xml
      feedLimit: 10
      position:
        top: 0
        left: 3
        width: 2
        height: 3
      updateInterval: 14400
    power:
      enabled: true
      position:
        top: 1
        left: 8
        height: 1
        width: 2
      refreshInterval: 15
      title: "⚡️"
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 12
      position:
        top: 1
        left: 0
        height: 2
        width: 3
      storyType: top
      refreshInterval: 900  
    devto:
      enabled: true
      numberOfArticles: 10
      position:
        top: 3
        left: 0
        height: 1
        width: 3
      contentState: "rising"
    github:
      apiKey: "45d6c34982a2c3b95922f8671d250d1375eea270"
      baseURL: ""
      customQueries:
      othersPRs:
        title: "Others Pull Requests"
        filter: "is:open is:pr"
      enabled: true
      enableStatus: true
      position:
        top: 2
        left: 8
        height: 2
        width: 3
      refreshInterval: 300
      repositories:
        - "percypike3823/dots"
        - "percypike3823/python-zaid"
        - "zdharma/zinit"
      showStats: false
      username: "percypike10@hotmail.com"
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 2
        left: 5
        height: 1
        width: 3
      refreshInterval: 1
    uptime:
      type: cmdrunner
      args: [""]
      cmd: "uptime"
      enabled: false
      position:
        top: 1
        left: 8
        height: 1
        width: 1
      refreshInterval: 30
    disks:
      type: cmdrunner
      cmd: "df"
      args: ["-h"]
      enabled: true
      position:
        top: 0
        left: 5
        height: 1
        width: 3
      refreshInterval: 3600
    textfile:
      enabled: true
      title: "Terminal"
      filePaths:
        - "~/Documents/Terminal.txt"
      format: true
      formatStyle: "solarized-dark"
      position:
        top: 1
        left: 5
        height: 1
        width: 3
      refreshInterval: 15
      wrapText: true
    hacking_subreddit:
      enabled: true
      numberOfPosts: 15
      position:
        top: 4
        left: 0
        height: 2
        width: 3
      sortOrder: top
      subreddit: "hacking"
      topTimePeriod: week
      refreshInterval: 900
      type: subreddit 
    coding_subreddit:
      enabled: true
      numberOfPosts: 15
      position:
        top: 6
        left: 0
        height: 2
        width: 3
      sortOrder: top
      subreddit: "coding"
      topTimePeriod: week
      refreshInterval: 900
      type: subreddit 
    news_subreddit:
      enabled: true
      numberOfPosts: 50
      position:
        top: 3
        left: 3
        height: 7
        width: 3
      sortOrder: hot
      subreddit: "news"
      topTimePeriod: week
      refreshInterval: 900
      type: subreddit 
    sensors: 
      title: Sensors
      type: cmdrunner
      args: ["BAT0-acpi-0", "fam15h_power-pci-00c4", "k10temp-pci-00c3", "amdgpu-pci-0008", "acpitz-acpi-0"]
      cmd: "sensors"
      enabled: true
      position: 
        height: 7
        left: 6
        top: 3
        width: 2
      refreshInterval: 30
      tail: true
    cmdrunner:
      args: ["-s", "-t"]
      cmd: "ss"
      enabled: true
      position:
        top: 4
        left: 8
        height: 4
        width: 3
    refreshInterval: 30